# Read version from file
VERSION ?= $(shell cat VERSION)
# Base Image Name
IMG_BASE ?= hvtung/k8s-docker-operator

# Bump version
bump:
	@echo "Current version: $(VERSION)"
	@new_ver=$$(echo $(VERSION) | sed 's/^v//' | awk -F. '{print $$1"."$$2"."$$3+1}'); \
	echo "v$$new_ver" > VERSION; \
	echo "Bumped version to v$$new_ver"
	@echo "New version: $$(cat VERSION)"

# Get the currently used golang install path (in GOPATH/bin, unless GOBIN is set)
ifeq (,$(shell go env GOBIN))
GOBIN=$(shell go env GOPATH)/bin
else
GOBIN=$(shell go env GOBIN)
endif

all: build

# Run tests
test:
	go test ./... -coverprofile cover.out

# Build manager binary
build:
	go build -o bin/manager cmd/manager/main.go

# Run against the configured Kubernetes cluster in ~/.kube/config
run: install
	go run ./cmd/manager/main.go

# Install CRDs into a cluster
install:
	kubectl apply -f config/crd/bases/app.example.com_composeapps.yaml

# Uninstall CRDs from a cluster
uninstall:
	kubectl delete -f config/crd/bases/app.example.com_composeapps.yaml

# Build the docker image
docker-build:
	$(MAKE) bump
	docker build . -t ${IMG_BASE}:$$(cat VERSION)

# Push the docker image
docker-push:
	docker push ${IMG_BASE}:$$(cat VERSION)

# Build multi-platform docker image using buildx
PLATFORMS ?= linux/amd64,linux/arm64
docker-buildx:
	$(MAKE) bump
	docker buildx build --platform $(PLATFORMS) . -t ${IMG_BASE}:$$(cat VERSION) --push

# Generate install manifests
dist:
	@echo "Generating install/install.yaml..."
	@mkdir -p install
	@echo "# Generated by make dist on $$(date)" > install/install.yaml
	@echo "# Version: $$(cat VERSION)" >> install/install.yaml
	@echo "---" >> install/install.yaml
	@cat config/manager/namespace.yaml >> install/install.yaml
	@echo "---" >> install/install.yaml
	@for f in config/crd/bases/*.yaml; do cat $$f; echo "---"; done >> install/install.yaml
	@for f in config/rbac/*.yaml; do cat $$f; echo "---"; done >> install/install.yaml
	@for f in config/gateway/*.yaml; do cat $$f; echo "---"; done >> install/install.yaml
	@cat config/manager/manager.yaml >> install/install.yaml
	@# Replace IMG_PLACEHOLDER in the final file
	@sed -i '' "s|IMG_PLACEHOLDER|${IMG_BASE}:$$(cat VERSION)|g" install/install.yaml
	@echo "Install manifest generated at install/install.yaml"
	@echo "Generating install/kind-setup.yaml..."
	@echo "# Kind Cluster Setup (Docker Proxy + Default Host)" > install/kind-setup.yaml
	@cat config/docker_proxy.yaml >> install/kind-setup.yaml
	@echo "---" >> install/kind-setup.yaml
	@cat examples/dockerhost-default.yaml >> install/kind-setup.yaml
	@echo "Kind setup manifest generated at install/kind-setup.yaml"

# Release (Build, Push, Dist)
release:
	$(MAKE) docker-build
	$(MAKE) docker-push
	$(MAKE) dist

# Generate code
generate: controller-gen
	$(CONTROLLER_GEN) object:headerFile="hack/boilerplate.go.txt" paths="./..."

# Generate manifests e.g. CRD, RBAC etc.
manifests: controller-gen
	$(CONTROLLER_GEN) rbac:roleName=manager-role crd paths="./..." output:crd:artifacts:config=config/crd/bases

# Location to install dependencies to
LOCALBIN ?= $(shell pwd)/bin
$(LOCALBIN):
	mkdir -p $(LOCALBIN)

# Tool Binaries
CONTROLLER_GEN ?= $(LOCALBIN)/controller-gen

# Download controller-gen locally if necessary
.PHONY: controller-gen
controller-gen: $(CONTROLLER_GEN)
$(CONTROLLER_GEN): $(LOCALBIN)
	test -s $(LOCALBIN)/controller-gen || GOBIN=$(LOCALBIN) go install sigs.k8s.io/controller-tools/cmd/controller-gen@latest
