apiVersion: app.example.com/v1alpha1
kind: DockerContainer
metadata:
  name: nginx-secret
spec:
  image: "nginx:latest"
  containerName: "nginx-with-secrets"
  # Mapping Secret Keys to Environment Variables
  envVars:
    - name: DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: my-test-secret
          key: password
    - name: API_KEY
      valueFrom:
        secretKeyRef:
          name: my-test-secret
          key: api-key
  # Mapping Secret to a Volume (Files)
  secretVolumes:
    - secretName: my-test-secret
      mountPath: "/etc/secrets"
